language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean install -DskipTests"
- "./mvnw jib:build -P deploy-docker"
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: Ae2qlQwaZiIy0FEK9oMAX2DjBem0r9tLpgv7Eh7Hgmp49swktz/yx5F/7VBNzXbjU/nzbDVQQH0OKAeBps2XJ4u09ztHvGDR0oFMbZqMtTpgDobhcr5yGqQupsgoSa5phI3ek/RjnMYBzJW0cdIbFOMQcha3u5qYzK8kdRAhbepdcFtwhNUJHdq4kUG6015zvrzA4xmy6PFo1HUPEIFniHbtsexWokeP//uIid7i0YRPpS1AD9ZpIFu5cjkz6PPEKGBFOJ8yf4tfks4Vca9KLsUtPXl5cGyOdbyRwwoN00v/S6L4yArjwD8VMgcoDB/KZjswbbLmakVw1+Tut71FpzSO1QF4ONNfd1j2BAAfZdxCgt21TEpt+m2qcXGuH0PyAGkpg5QdgcyEhwTVNsgifgg7pF6+Vgw3amja0pLhOjGHhv5uMBKScQmcW5JWKwb2oDSYpsIBHLg7jnaGyz2dkAUHFWBS0UGtj7XnQer1cfDOK/siGjZQiVEUyCcfgYX8i21sC+P4mhd+8VgVMPI6GML5/PRZhpo/MN42BlpFi35vDgV6u4gFZ/rhQVUHKLvyW78FcPeZncdOBGVXQGWSf43dQ3AfQ/Q3kA8ukkXgQPo8zO3w2194Pz+4Qx2hSPUxgw44/Wkpd5r5LnXbe+dqbM4TdYutnm5GL6h8CLMV+AQ=
  app: petvet-api
