CREATE TABLE veterinary(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	profile VARCHAR(20) NOT NULL,
	enabled BOOLEAN NOT NULL,
	creation_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	avatar VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;